# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\Workspace\PyQtClient\UiFiles\ErrorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormErrorDialog(object):
    def setupUi(self, FormErrorDialog):
        FormErrorDialog.setObjectName("FormErrorDialog")
        FormErrorDialog.resize(600, 406)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormErrorDialog)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetError = QtWidgets.QWidget(FormErrorDialog)
        self.widgetError.setProperty("active", True)
        self.widgetError.setObjectName("widgetError")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetError)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dialogTitlebar = QtWidgets.QWidget(self.widgetError)
        self.dialogTitlebar.setObjectName("dialogTitlebar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dialogTitlebar)
        self.horizontalLayout.setContentsMargins(0, 1, 1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTitle = QtWidgets.QLabel(self.dialogTitlebar)
        self.labelTitle.setIndent(6)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(260, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonClose = QtWidgets.QPushButton(self.dialogTitlebar)
        self.buttonClose.setText("")
        self.buttonClose.setAutoDefault(False)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout.addWidget(self.buttonClose)
        self.verticalLayout_2.addWidget(self.dialogTitlebar)
        self.widgetErrorBg = QtWidgets.QStackedWidget(self.widgetError)
        self.widgetErrorBg.setObjectName("widgetErrorBg")
        self.pageError = QtWidgets.QWidget()
        self.pageError.setObjectName("pageError")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageError)
        self.verticalLayout_3.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEditDetail = QtWidgets.QPlainTextEdit(self.pageError)
        self.plainTextEditDetail.setMinimumSize(QtCore.QSize(0, 250))
        self.plainTextEditDetail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEditDetail.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEditDetail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEditDetail.setUndoRedoEnabled(False)
        self.plainTextEditDetail.setReadOnly(True)
        self.plainTextEditDetail.setObjectName("plainTextEditDetail")
        self.verticalLayout_3.addWidget(self.plainTextEditDetail)
        self.widget = QtWidgets.QWidget(self.pageError)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.buttonInstall = QtWidgets.QPushButton(self.widget)
        self.buttonInstall.setAutoDefault(False)
        self.buttonInstall.setObjectName("buttonInstall")
        self.horizontalLayout_2.addWidget(self.buttonInstall)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.widget)
        self.widgetErrorBg.addWidget(self.pageError)
        self.pagePip = QtWidgets.QWidget()
        self.pagePip.setObjectName("pagePip")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pagePip)
        self.verticalLayout_4.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEditPip = QtWidgets.QLineEdit(self.pagePip)
        self.lineEditPip.setObjectName("lineEditPip")
        self.verticalLayout_4.addWidget(self.lineEditPip)
        self.plainTextEditPip = QtWidgets.QPlainTextEdit(self.pagePip)
        self.plainTextEditPip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEditPip.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEditPip.setObjectName("plainTextEditPip")
        self.verticalLayout_4.addWidget(self.plainTextEditPip)
        self.widgetErrorBg.addWidget(self.pagePip)
        self.verticalLayout_2.addWidget(self.widgetErrorBg)
        self.verticalLayout.addWidget(self.widgetError)

        self.retranslateUi(FormErrorDialog)
        self.widgetErrorBg.setCurrentIndex(0)
        self.buttonClose.clicked.connect(FormErrorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FormErrorDialog)

    def retranslateUi(self, FormErrorDialog):
        _translate = QtCore.QCoreApplication.translate
        FormErrorDialog.setWindowTitle(_translate("FormErrorDialog", "Error"))
        self.labelTitle.setText(_translate("FormErrorDialog", "Error"))
        self.buttonInstall.setText(_translate("FormErrorDialog", "Install Requirements"))
        self.lineEditPip.setPlaceholderText(_translate("FormErrorDialog", "Module Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormErrorDialog = QtWidgets.QDialog()
    ui = Ui_FormErrorDialog()
    ui.setupUi(FormErrorDialog)
    FormErrorDialog.show()
    sys.exit(app.exec_())

