# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\Workspace\PyQtClient\UiFiles\IssuesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormIssuesDialog(object):
    def setupUi(self, FormIssuesDialog):
        FormIssuesDialog.setObjectName("FormIssuesDialog")
        FormIssuesDialog.resize(800, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormIssuesDialog)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetIssues = QtWidgets.QWidget(FormIssuesDialog)
        self.widgetIssues.setProperty("active", True)
        self.widgetIssues.setObjectName("widgetIssues")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetIssues)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dialogTitlebar = QtWidgets.QWidget(self.widgetIssues)
        self.dialogTitlebar.setObjectName("dialogTitlebar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dialogTitlebar)
        self.horizontalLayout.setContentsMargins(0, 1, 1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTitle = QtWidgets.QLabel(self.dialogTitlebar)
        self.labelTitle.setIndent(6)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(260, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonWebsite = QtWidgets.QPushButton(self.dialogTitlebar)
        self.buttonWebsite.setAutoDefault(False)
        self.buttonWebsite.setObjectName("buttonWebsite")
        self.horizontalLayout.addWidget(self.buttonWebsite)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonClose = QtWidgets.QPushButton(self.dialogTitlebar)
        self.buttonClose.setText("")
        self.buttonClose.setAutoDefault(False)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout.addWidget(self.buttonClose)
        self.verticalLayout_2.addWidget(self.dialogTitlebar)
        self.widgetMain = QtWidgets.QWidget(self.widgetIssues)
        self.widgetMain.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widgetMain.setObjectName("widgetMain")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetMain)
        self.verticalLayout_3.setContentsMargins(30, 15, 30, 20)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelTip = QtWidgets.QLabel(self.widgetMain)
        self.labelTip.setObjectName("labelTip")
        self.verticalLayout_3.addWidget(self.labelTip)
        self.plainTextEditIssues = QtWidgets.QPlainTextEdit(self.widgetMain)
        self.plainTextEditIssues.setMinimumSize(QtCore.QSize(0, 245))
        self.plainTextEditIssues.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.plainTextEditIssues.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEditIssues.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEditIssues.setObjectName("plainTextEditIssues")
        self.verticalLayout_3.addWidget(self.plainTextEditIssues)
        self.widget_2 = QtWidgets.QWidget(self.widgetMain)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonScreenshot = QtWidgets.QPushButton(self.widget_2)
        self.buttonScreenshot.setAutoDefault(False)
        self.buttonScreenshot.setObjectName("buttonScreenshot")
        self.horizontalLayout_2.addWidget(self.buttonScreenshot)
        self.buttonAttach = QtWidgets.QPushButton(self.widget_2)
        self.buttonAttach.setAutoDefault(False)
        self.buttonAttach.setObjectName("buttonAttach")
        self.horizontalLayout_2.addWidget(self.buttonAttach)
        self.verticalLayout_3.addWidget(self.widget_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.widget_3 = QtWidgets.QWidget(self.widgetMain)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.buttonComment = QtWidgets.QPushButton(self.widget_3)
        self.buttonComment.setAutoDefault(False)
        self.buttonComment.setObjectName("buttonComment")
        self.horizontalLayout_3.addWidget(self.buttonComment)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.widgetMain)
        self.verticalLayout.addWidget(self.widgetIssues)

        self.retranslateUi(FormIssuesDialog)
        self.buttonClose.clicked.connect(FormIssuesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FormIssuesDialog)

    def retranslateUi(self, FormIssuesDialog):
        _translate = QtCore.QCoreApplication.translate
        FormIssuesDialog.setWindowTitle(_translate("FormIssuesDialog", "Issues"))
        self.labelTitle.setText(_translate("FormIssuesDialog", "Issues"))
        self.buttonWebsite.setText(_translate("FormIssuesDialog", "Issues Website"))
        self.labelTip.setText(_translate("FormIssuesDialog", "Do you have any questions or suggestions for us?"))
        self.plainTextEditIssues.setToolTip(_translate("FormIssuesDialog", "Describing your problem in detail, will help us solve the problem quickly. For example:\n"
"1. What did you do before the problem occurred?\n"
"2. Report error log files, They are in Resources/Data/app.log and Resources/Data/Errors"))
        self.plainTextEditIssues.setPlaceholderText(_translate("FormIssuesDialog", "Describing your problem in detail, will help us solve the problem quickly."))
        self.buttonScreenshot.setText(_translate("FormIssuesDialog", "Screenshot"))
        self.buttonAttach.setText(_translate("FormIssuesDialog", "Attach files"))
        self.buttonComment.setText(_translate("FormIssuesDialog", "Comment"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormIssuesDialog = QtWidgets.QDialog()
    ui = Ui_FormIssuesDialog()
    ui.setupUi(FormIssuesDialog)
    FormIssuesDialog.show()
    sys.exit(app.exec_())

