# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\Workspace\PyQtClient\UiFiles\LoginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormLoginDialog(object):
    def setupUi(self, FormLoginDialog):
        FormLoginDialog.setObjectName("FormLoginDialog")
        FormLoginDialog.resize(314, 422)
        FormLoginDialog.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormLoginDialog)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetLogin = QtWidgets.QWidget(FormLoginDialog)
        self.widgetLogin.setProperty("active", True)
        self.widgetLogin.setObjectName("widgetLogin")
        self.gridLayout = QtWidgets.QGridLayout(self.widgetLogin)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.widgetLoginEdit = QtWidgets.QWidget(self.widgetLogin)
        self.widgetLoginEdit.setObjectName("widgetLoginEdit")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetLoginEdit)
        self.verticalLayout_2.setContentsMargins(25, 0, 25, 0)
        self.verticalLayout_2.setSpacing(18)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditAccount = QtWidgets.QLineEdit(self.widgetLoginEdit)
        self.lineEditAccount.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditAccount.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEditAccount.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditAccount.setObjectName("lineEditAccount")
        self.verticalLayout_2.addWidget(self.lineEditAccount)
        self.lineEditPassword = QtWidgets.QLineEdit(self.widgetLoginEdit)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditPassword.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout_2.addWidget(self.lineEditPassword)
        self.labelNotice = QtWidgets.QLabel(self.widgetLoginEdit)
        self.labelNotice.setMinimumSize(QtCore.QSize(0, 20))
        self.labelNotice.setText("")
        self.labelNotice.setObjectName("labelNotice")
        self.verticalLayout_2.addWidget(self.labelNotice)
        self.buttonLogin = ProgressButton(self.widgetLoginEdit)
        self.buttonLogin.setMinimumSize(QtCore.QSize(0, 36))
        self.buttonLogin.setMaximumSize(QtCore.QSize(16777215, 36))
        self.buttonLogin.setObjectName("buttonLogin")
        self.verticalLayout_2.addWidget(self.buttonLogin)
        self.gridLayout.addWidget(self.widgetLoginEdit, 4, 0, 1, 3)
        self.dialogTitlebar = QtWidgets.QWidget(self.widgetLogin)
        self.dialogTitlebar.setObjectName("dialogTitlebar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dialogTitlebar)
        self.horizontalLayout.setContentsMargins(0, 1, 1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(260, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.buttonClose = QtWidgets.QPushButton(self.dialogTitlebar)
        self.buttonClose.setText("")
        self.buttonClose.setAutoDefault(False)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout.addWidget(self.buttonClose)
        self.gridLayout.addWidget(self.dialogTitlebar, 0, 0, 1, 3)
        self.widgetLoginBottom = QtWidgets.QWidget(self.widgetLogin)
        self.widgetLoginBottom.setMinimumSize(QtCore.QSize(0, 54))
        self.widgetLoginBottom.setObjectName("widgetLoginBottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetLoginBottom)
        self.horizontalLayout_2.setContentsMargins(28, 0, 28, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelRegister = QtWidgets.QLabel(self.widgetLoginBottom)
        self.labelRegister.setOpenExternalLinks(True)
        self.labelRegister.setObjectName("labelRegister")
        self.horizontalLayout_2.addWidget(self.labelRegister)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.labelForgot = QtWidgets.QLabel(self.widgetLoginBottom)
        self.labelForgot.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelForgot.setOpenExternalLinks(True)
        self.labelForgot.setObjectName("labelForgot")
        self.horizontalLayout_2.addWidget(self.labelForgot)
        self.gridLayout.addWidget(self.widgetLoginBottom, 6, 0, 1, 3)
        self.buttonHead = RotateButton(self.widgetLogin)
        self.buttonHead.setText("")
        self.buttonHead.setObjectName("buttonHead")
        self.gridLayout.addWidget(self.buttonHead, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.widgetLogin)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)

        self.retranslateUi(FormLoginDialog)
        self.lineEditPassword.returnPressed.connect(self.buttonLogin.click)
        self.buttonClose.clicked.connect(FormLoginDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FormLoginDialog)

    def retranslateUi(self, FormLoginDialog):
        _translate = QtCore.QCoreApplication.translate
        FormLoginDialog.setWindowTitle(_translate("FormLoginDialog", "Login"))
        self.lineEditAccount.setPlaceholderText(_translate("FormLoginDialog", "Github Account"))
        self.lineEditPassword.setPlaceholderText(_translate("FormLoginDialog", "Github Password"))
        self.buttonLogin.setText(_translate("FormLoginDialog", "Login"))
        self.labelRegister.setText(_translate("FormLoginDialog", "<html><head/><body><p><a href=\"https://github.com/join?source=login\"><span style=\" text-decoration: none; color:#ffffff;\">Register</span></a></p></body></html>"))
        self.labelForgot.setText(_translate("FormLoginDialog", "<html><head/><body><p><a href=\"https://github.com/password_reset\"><span style=\" text-decoration: none; color:#e6e6e6;\">Forgot?</span></a></p></body></html>"))

from Widgets.Buttons.ProgressButton import ProgressButton
from Widgets.Buttons.RotateButton import RotateButton

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormLoginDialog = QtWidgets.QDialog()
    ui = Ui_FormLoginDialog()
    ui.setupUi(FormLoginDialog)
    FormLoginDialog.show()
    sys.exit(app.exec_())

