# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\Workspace\PyQtClient\UiFiles\SkinDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormSkinDialog(object):
    def setupUi(self, FormSkinDialog):
        FormSkinDialog.setObjectName("FormSkinDialog")
        FormSkinDialog.resize(916, 635)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormSkinDialog)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetSkin = QtWidgets.QWidget(FormSkinDialog)
        self.widgetSkin.setProperty("active", True)
        self.widgetSkin.setObjectName("widgetSkin")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetSkin)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dialogTitlebar = QtWidgets.QWidget(self.widgetSkin)
        self.dialogTitlebar.setObjectName("dialogTitlebar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dialogTitlebar)
        self.horizontalLayout.setContentsMargins(0, 1, 1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTitle = QtWidgets.QLabel(self.dialogTitlebar)
        self.labelTitle.setIndent(6)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(260, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonClose = QtWidgets.QPushButton(self.dialogTitlebar)
        self.buttonClose.setText("")
        self.buttonClose.setAutoDefault(False)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout.addWidget(self.buttonClose)
        self.verticalLayout_2.addWidget(self.dialogTitlebar)
        self.widgetSkinBg = QtWidgets.QWidget(self.widgetSkin)
        self.widgetSkinBg.setObjectName("widgetSkinBg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetSkinBg)
        self.verticalLayout_3.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidgetSkinMain = QtWidgets.QTabWidget(self.widgetSkinBg)
        self.tabWidgetSkinMain.setObjectName("tabWidgetSkinMain")
        self.tabTheme = ThemeWidget()
        self.tabTheme.setObjectName("tabTheme")
        self.tabWidgetSkinMain.addTab(self.tabTheme, "")
        self.tabColourful = ColourfulWidget()
        self.tabColourful.setObjectName("tabColourful")
        self.tabWidgetSkinMain.addTab(self.tabColourful, "")
        self.tabPicture = QtWidgets.QWidget()
        self.tabPicture.setObjectName("tabPicture")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabPicture)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.tabPicture)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(30, 10, 30, 10)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widgetCategories = QtWidgets.QWidget(self.widget)
        self.widgetCategories.setObjectName("widgetCategories")
        self.verticalLayout_5.addWidget(self.widgetCategories)
        self.verticalLayout_4.addWidget(self.widget)
        self.stackedWidgetPictures = QtWidgets.QStackedWidget(self.tabPicture)
        self.stackedWidgetPictures.setObjectName("stackedWidgetPictures")
        self.verticalLayout_4.addWidget(self.stackedWidgetPictures)
        self.tabWidgetSkinMain.addTab(self.tabPicture, "")
        self.verticalLayout_3.addWidget(self.tabWidgetSkinMain)
        self.widgetBottom = QtWidgets.QWidget(self.widgetSkinBg)
        self.widgetBottom.setMinimumSize(QtCore.QSize(0, 64))
        self.widgetBottom.setObjectName("widgetBottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetBottom)
        self.horizontalLayout_2.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout_2.setSpacing(14)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widgetBottom)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.sliderOpacity = QtWidgets.QSlider(self.widgetBottom)
        self.sliderOpacity.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sliderOpacity.setMaximum(100)
        self.sliderOpacity.setPageStep(1)
        self.sliderOpacity.setProperty("value", 100)
        self.sliderOpacity.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOpacity.setInvertedAppearance(True)
        self.sliderOpacity.setObjectName("sliderOpacity")
        self.horizontalLayout_2.addWidget(self.sliderOpacity)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.buttonRestore = QtWidgets.QPushButton(self.widgetBottom)
        self.buttonRestore.setAutoDefault(False)
        self.buttonRestore.setObjectName("buttonRestore")
        self.horizontalLayout_2.addWidget(self.buttonRestore)
        self.verticalLayout_3.addWidget(self.widgetBottom)
        self.verticalLayout_2.addWidget(self.widgetSkinBg)
        self.verticalLayout.addWidget(self.widgetSkin)

        self.retranslateUi(FormSkinDialog)
        self.tabWidgetSkinMain.setCurrentIndex(0)
        self.buttonClose.clicked.connect(FormSkinDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FormSkinDialog)

    def retranslateUi(self, FormSkinDialog):
        _translate = QtCore.QCoreApplication.translate
        FormSkinDialog.setWindowTitle(_translate("FormSkinDialog", "Skin"))
        self.labelTitle.setText(_translate("FormSkinDialog", "Skin"))
        self.tabWidgetSkinMain.setTabText(self.tabWidgetSkinMain.indexOf(self.tabTheme), _translate("FormSkinDialog", "Theme"))
        self.tabWidgetSkinMain.setTabText(self.tabWidgetSkinMain.indexOf(self.tabColourful), _translate("FormSkinDialog", "Colourful"))
        self.tabWidgetSkinMain.setTabText(self.tabWidgetSkinMain.indexOf(self.tabPicture), _translate("FormSkinDialog", "Picture"))
        self.label.setText(_translate("FormSkinDialog", "Transparency"))
        self.buttonRestore.setText(_translate("FormSkinDialog", "Restore the default theme"))

from Widgets.Skins.ColourfulWidget import ColourfulWidget
from Widgets.Skins.ThemeWidget import ThemeWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormSkinDialog = QtWidgets.QDialog()
    ui = Ui_FormSkinDialog()
    ui.setupUi(FormSkinDialog)
    FormSkinDialog.show()
    sys.exit(app.exec_())

